title: Cats Win People 
author: GitHub Lord 
email: githubmaster@domain.com
description: > # this means to ignore newlines until "baseurl:"
This site will talk about what's important in life. 
Like a religious show but much better. 
Animals are important. 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
